### ISSUE TITLE
Cannot save a mapview object

### ISSUE THREAD

**Issue by Nowosad** [bhaskarvk/widgetframe#10]
``` r
library(mapview)
#> Loading required package: leaflet
library(widgetframe)
#> Loading required package: htmlwidgets
m = mapview(breweries)
saveWidget(m, "temp.html", selfcontained = FALSE)
#> Error in x$width: $ operator not defined for this S4 class
```

I've tried to save a mapview object to a file and got the above error. Is it a problem of widgetframe or mapview?

**Comment by bhaskarvk** [comment]
if you're saving this to be displayed like we discussed on Twitter, then you don't even need   widgetframe. You can just use htmlwidgets::saveWidget w/o loading widgetframe. Also specific to this error, try passing in the width argument. Also does mapview return a widget or some other class?

**Comment by Nowosad** [comment]
Ok, I think I've found the solution - https://rdrr.io/cran/mapview/man/mapshot.html. 
Nonetheless, thanks for all the help @bhaskarvk !
