### ISSUE TITLE
scrolling DT::datatable

### ISSUE THREAD

**Issue by jcolomb** [bhaskarvk/widgetframe#16]
hey,
I want to have a DT::datatable in my blogdown website. widgetframe make it possible, but my tables are larger than the width of a page and it does not scroll horizontally once into the widgetframe.

Any idea how to work around that ?

**Comment by jcolomb** [comment]
A workaround is to use datatable scrolling extensions:

```
DT::datatable(
  datahere,
extensions = list('FixedColumns',
                    'Scroller'),
  
  options = list(
    deferRender = TRUE,
    scrollY = 200,
    scroller = TRUE
    ,
    dom = 't',
    scrollX = TRUE,
    
    fixedColumns = TRUE
  )
```

**Comment by bhaskarvk** [comment]
Closing as workaround is available. Reopen if necessary
