### ISSUE TITLE
Using widgetframe in md files

### ISSUE THREAD

**Issue by stephlocke** [bhaskarvk/widgetframe#17]
Heya 😄 
I'm looking to incorporate a htmlwidget into pages that'll be included in Hugo.  I'm trying to do Rmd -> md conversions (for lightness of deps). 

When I use widgetframe with a htmlwidget, I'm not ending up with iframe code. I read the vignette and I'm not sure if I'm doing something wrong - would you be able to advise?

I put a sample doc on [gist](https://gist.github.com/stephlocke/1bc4b2403978abc11596395200007eb1) but in essence in my md file I'm only getting the following output when I run `frameWidget()`
```
<!--html_preserve-->

<script type="application/json" data-for="htmlwidget-ee9240b3e9cf31cad221">{"x":{"url":"exampleframewidget_files/figure-markdown_github//widgets/widget_unnamed-chunk-4.html","options":{"xdomain":"*","allowfullscreen":false,"lazyload":false}},"evals":[],"jsHooks":[]}</script>
<!--/html_preserve-->
```

No iframe or associated js code for the json. Thanks for any guidance you can give!

**Comment by bhaskarvk** [comment]
Rmd to HTML is the only way to go, and that's a limitation of htmlwidgets not widgetframe. Ping htmlwidgets authors they may be able to offer some insights in this matter.
