### ISSUE TITLE
returning html instead of widget

### ISSUE THREAD

**Issue by yonicd** [bhaskarvk/widgetframe#4]
continuation of [issue](https://github.com/ramnathv/htmlwidgets/issues/261#issuecomment-285958356) opened in htmlwidgets repo. 

i wrote an htmlwidget [slickR](https://github.com/yonicd/slickR) binding slickjs. i allowed input for iframes in the call to the widget, and they need to be in a character vector where the objects are html lines. 

example (open in browser not viewer if not using rstudio server):

```
devtools::install_github('yonicd/slickR')
geom_filenames=ls("package:ggplot2",pattern = '^geom')
inputObj=unlist(lapply(geom_filenames,getHelp,pkg = 'ggplot2'))

inputObj[1]

slickR(inputObj,slideType = 'iframe',height = '0px',
slickOpts = list(dots=T,slidesToShow=2,slidesToScroll=2))
```

since i can input an iframe i thought a continuation would be to nest self contained htmlwidgets in iframes and run them in a carousel.

can i do this with just a call to widgetframe or do i need to write in my widget the same bindings for pym.js, like `var pymParent = new pym.Parent('divId', x.url, {});`?

**Comment by yonicd** [comment]
nm got it.

```
library(leaflet)
library(widgetframe)
library(slickR)

l <- leaflet() %>% addTiles()
htmlwidgets::saveWidget(frameableWidget(l),'leaflet.html')

slickR(rep(paste0(readLines('leaflet.html'),collapse='\n'),4),slideType = rep('iframe',2),slickOpts = list(dots=T,slidesToShow=2,slidesToScroll=2))
```

**Comment by bhaskarvk** [comment]
Yup I was going to suggest the same for you. Cool that you got it on your own.
Btw if slickR is already taking care of adding the `<iframe>` HTML element, you may not need widgetframe after all.
You can simply do

```r
library(leaflet)
library(widgetframe)
library(slickR)

l <- leaflet() %>% addTiles()
htmlwidgets::saveWidget(l,'leaflet.html')

slickR(rep(paste0(readLines('leaflet.html'),collapse='\n'),4),slideType = rep('iframe',2),slickOpts = list(dots=T,slidesToShow=2,slidesToScroll=2))
```

The only thing frameableWidget does is add the pym.js child initialization code, which you may not need if slickR is not using pym.js.

**Comment by yonicd** [comment]
you are right. thanks!

**Comment by bhaskarvk** [comment]
Btw if you do end up using widgetframe, do setup Pym.js and Parent in the parent widget, it will give you responsive iframes, which are really nice.

**Comment by yonicd** [comment]
responsive in what way? resizing?

kent russell just fixed my js code to get slick to run in rmarkdown. so now it works in rmarkdown and shiny.

**Comment by yonicd** [comment]
hey. 

this doesnt give a reactive html anymore

```r
library(leaflet)
library(dplyr)
l <- leaflet() %>% addTiles()
htmlwidgets::saveWidget(l,'leaflet.html')
```

what could be the reason?
