### ISSUE TITLE
Following render()'s self_contained FALSE and lib_dir

### ISSUE THREAD

**Issue by jsonbecker** [bhaskarvk/widgetframe#5]
When using `render(self_contained = FALSE, lib_dir = X)`, frameWidget does not place dependencies in `lib_dir` or the html output into the tradition `X_files/` folder like other assets, instead both are always placed in the working directory.

**Comment by bhaskarvk** [comment]
Hi I am revisiting this bug, could you provide a small reproducible Rmd file ?

**Comment by bhaskarvk** [comment]
I've fixed this in the master, but working on properly documenting the code. Will keep it open for now, but feel free to build from master and check it out. FYI do checkout some of the options that I pass to knitr in the examples folder.

**Comment by bhaskarvk** [comment]
Fixed in 0.2.0 and released on CRAN
