### ISSUE TITLE
widgetframe in bookdown css problem

### ISSUE THREAD

**Issue by yonicd** [bhaskarvk/widgetframe#6]
I am trying to use slickR in a bookdown but I am getting the same css problem you talked about in [SO](http://stackoverflow.com/questions/40982137/css-customization-in-a-bookdown-document), and pointed to a annotated css.style for leaflet in [gist](https://gist.github.com/bhaskarvk/acc14421598d76f65da6a2c153a07865). I tried doing something similar and put the style.css in ./css/style.css. 

Did I miss anything? where did you put your style.css? could widgetframe solve this?

**Comment by bhaskarvk** [comment]
That CSS was before I wrote widgetframe, and it's not really an ideal solution.
I wrote widgetframe explicitly to solve that issue. But there's an outstanding issue in bookdown https://github.com/rstudio/bookdown/issues/271 and in blogdown https://github.com/rstudio/blogdown/issues/38 that prevents widgetframes from working correctly with bookdown/blogdown.

If you are using iframe in slickR, then the stuff inside your iframe will not be affected by bookdown's CSS anyways regardless whether you use widgetframe or not.
But if your content is not in an iframe then you will need to provide your own css like I did in that SO thread. You will also need to have something like below in your `_output.yml` file

```yaml
bookdown::gitbook:
  css: ['your-css-file']
```

**Comment by yonicd** [comment]
my problem are the dot icons for the slick. they come out tiny because of the bookdown css. an iframe wouldnt solve that.

thanks for the answer.

**Comment by bhaskarvk** [comment]
Yeah in that case put your css in `./css/style.css` and add the following to your `_output.yml` file.

```yaml
bookdown::gitbook:
  css: ['css/style.css']
``` 

Also don't forget to add `! important` to your stuff in the css file so that those rules take precedence over everything else.

**Comment by yonicd** [comment]
do i need to still add the path prefix to all styles in the css? ie. `.book .book-body .page-wrapper .page-inner section.normal`

**Comment by bhaskarvk** [comment]
If you add `! important` then you don't need to do that.

**Comment by bhaskarvk** [comment]
I was not aware of the `! important` feature when I rewrote the css in that SO post.

**Comment by yonicd** [comment]
worked! is there a way to set important on the whole file? ;)

**Comment by yonicd** [comment]
that would be a better question for Yihui

**Comment by bhaskarvk** [comment]
AFAIK, there's no way of doing a file wide `important` in CSS, you've to do it rule per rule.

**Comment by yonicd** [comment]
some [fruit of labor](https://metrumresearchgroup.github.io/slickR/index.html) . there are two small things i cant seem to solve. how to make rmarkdown create plot output files without showing putting them in the document and when I try to use synched carousels (a top main slide that shows only one and a bottom slide that is smaller but controls what you see on the top one) bookdown hides the lower one always even though it's in the html tree and is active.

**Comment by bhaskarvk** [comment]
Are you using widgetframe ? Or just plain iframe ?

**Comment by yonicd** [comment]
for the help files?
